This is makeindex, version 2.15 [TeX Live 2018] (kpathsea + Thai support).
Scanning style file ./memoire_main.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file memoire_main.acn....done (159 entries accepted, 0 rejected).
Sorting entries....done (1321 comparisons).
Generating output file memoire_main.acr....done (104 lines written, 0 warnings).
Output written in memoire_main.acr.
Transcript written in memoire_main.alg.
